version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
     - requirements: docs/requirements.txt  # 使用 requirements 文件

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false  